name: Continuous Integration

on:
    push:
        branches: ["**"]
        tags: ["v*"]

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "Setup Node"
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "yarn"
                  cache-dependency-path: "yarn.lock"
            - name: "Install dependencies"
              run: "yarn"
            - name: "Compile"
              run: "yarn run compile-only"
            # - name: "Run tests"
            #   run: "yarn run test"
            - name: "Linter"
              run: "yarn run lint"
            - name: "Check formatting"
              run: "yarn run formatter-check"

    build-and-deploy:
        runs-on: ubuntu-latest
        if: "startsWith(github.ref, 'refs/tags/v')"
        needs: ["test"]
        defaults:
            run:
                shell: bash
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "Setup Node"
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "yarn"
                  cache-dependency-path: "yarn.lock"
            - name: "Install dependencies"
              run: "yarn"
            - name: "Build app"
              run: "yarn run build"
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
                  user_name: "github-actions[bot]"
                  user_email: "github-actions[bot]@users.noreply.github.com"
                  force_orphan: true
